# Generated by Django 5.2.8 on 2025-12-05 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MTMHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hedge_type', models.CharField(max_length=20)),
                ('hedge_id', models.IntegerField()),
                ('date', models.DateField()),
                ('crop', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('hedge_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=14)),
                ('wallet_balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MTMRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hedge_type', models.CharField(default='FARMER', max_length=20)),
                ('hedge_id', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('crop', models.CharField(max_length=50)),
                ('hedge_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wallet_balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
