# Generated by Django 5.2.8 on 2025-12-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerhedge',
            name='margin_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
