# Generated by Django 5.2.8 on 2025-12-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_buyerhedge_margin_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerhedge',
            name='matched_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='buyerhedge',
            name='status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
    ]
