# Generated by Django 5.2.8 on 2025-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0004_buyerhedge_last_mtm_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerhedge',
            name='hedge_type',
            field=models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], default='CALL', max_length=10),
        ),
    ]
