# Generated by Django 5.2.8 on 2025-12-02 02:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerAadhaarKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerBusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('company_type', models.CharField(max_length=50)),
                ('gst_number', models.CharField(max_length=50)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=15)),
                ('factory_address', models.CharField(max_length=255)),
                ('intake_capacity', models.CharField(max_length=100)),
                ('prefers_groundnut', models.BooleanField(default=False)),
                ('prefers_soybean', models.BooleanField(default=False)),
                ('prefers_sunflower', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerTraderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trader_type', models.CharField(max_length=50)),
                ('shop_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('prefers_groundnut', models.BooleanField(default=False)),
                ('prefers_soybean', models.BooleanField(default=False)),
                ('prefers_sunflower', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('village', models.CharField(max_length=100)),
                ('mandal', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('land_size', models.CharField(max_length=50)),
                ('grows_groundnut', models.BooleanField(default=False)),
                ('grows_soybean', models.BooleanField(default=False)),
                ('grows_sunflower', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
