# Generated by Django 5.2.8 on 2025-12-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyertraderprofile',
            name='district',
            field=models.CharField(default='Guntur', max_length=255),
        ),
    ]
