# Generated by Django 5.2.8 on 2025-12-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmercontract',
            name='contract_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmercontract',
            name='buyer_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BUYER_ACCEPTED', 'Buyer Accepted'), ('FARMER_APPROVED', 'Farmer Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='BuyerAcceptedContract',
        ),
    ]
