# Generated by Django 5.2.8 on 2025-12-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_farmercontract_contract_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerhedge',
            name='margin_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
