# Generated by Django 5.2.8 on 2025-12-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_farmerhedge_margin_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerhedge',
            name='matched_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='farmerhedge',
            name='status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
    ]
