# Generated by Django 5.2.8 on 2025-12-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_farmerhedge_matched_quantity_farmerhedge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerhedge',
            name='last_mtm_pnl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
